// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Online_Clinic_Management_System.DBCONTEXT;

#nullable disable

namespace Online_Clinic_Management_System.Migrations.LabtestDb
{
    [DbContext(typeof(LabtestDbContext))]
    [Migration("20240402154317_Labtest")]
    partial class Labtest
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Online_Clinic_Management_System.Models.LabtestViewModel", b =>
                {
                    b.Property<int>("LabTest")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LabTest"));

                    b.Property<string>("TestCost")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LabTest");

                    b.ToTable("Labtest");
                });
#pragma warning restore 612, 618
        }
    }
}
